version: "3.7"
services:
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      -  ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: botusers

    ports:
      - "27017:27017"
    restart: always